---
- name: Modify index.html content
  become: yes
  template:
    src: templates/app/index.html.j2
    dest: "/app/index.html"
    owner: "root"
    group: "root"
    mode: 0755
  register: web_conf
  tags:
    - web_conf

